services:
  actual-server-nathan:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '5006:5006'
    environment:
      - ACTUAL_PORT=5006
      - ACTUAL_LOGIN_METHOD=openid
      - ACTUAL_OPENID_DISCOVERY_URL=${ACTUAL_OPENID_DISCOVERY_URL}
      - ACTUAL_OPENID_CLIENT_ID=${ACTUAL_OPENID_CLIENT_ID}
      - ACTUAL_OPENID_CLIENT_SECRET=${ACTUAL_OPENID_CLIENT_SECRET}
      - ACTUAL_OPENID_SERVER_HOSTNAME=${ACTUAL_OPENID_SERVER_HOSTNAME_NATHAN}
    volumes:
      - ${ACTUAL_BUDGET_NATHAN_DIR}/actual-data:/data
    healthcheck:
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  actual-server-cherise:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - '5007:5007'
    environment:
      - ACTUAL_PORT=5007
      - ACTUAL_LOGIN_METHOD=openid
      - ACTUAL_OPENID_DISCOVERY_URL=${ACTUAL_OPENID_DISCOVERY_URL}
      - ACTUAL_OPENID_CLIENT_ID=${ACTUAL_OPENID_CLIENT_ID}
      - ACTUAL_OPENID_CLIENT_SECRET=${ACTUAL_OPENID_CLIENT_SECRET}
      - ACTUAL_OPENID_SERVER_HOSTNAME=${ACTUAL_OPENID_SERVER_HOSTNAME_CHERISE}
    volumes:
      - ${ACTUAL_BUDGET_CHERISE_DIR}/actual-data:/data
    healthcheck:
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
