apiVersion: v1
kind: PersistentVolume
metadata:
  name: actual-budget-cherise-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tank/appdata/actual-budget-cherise/actual-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: actual-budget-cherise-pvc
  namespace: actual-budget
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: actual-budget-cherise-pv
  storageClassName: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actual-budget-cherise
  namespace: actual-budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actual-budget-cherise
  template:
    metadata:
      labels:
        app: actual-budget-cherise
    spec:
      containers:
        - name: actual-server
          image: docker.io/actualbudget/actual-server:latest
          ports:
            - containerPort: 5007
          env:
            - name: ACTUAL_PORT
              value: "5007"
            - name: ACTUAL_OPENID_DISCOVERY_URL
              valueFrom:
                secretKeyRef:
                  name: actual-budget-cherise
                  key: ACTUAL_OPENID_DISCOVERY_URL
            - name: ACTUAL_OPENID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: actual-budget-cherise
                  key: ACTUAL_OPENID_CLIENT_ID
            - name: ACTUAL_OPENID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: actual-budget-cherise
                  key: ACTUAL_OPENID_CLIENT_SECRET
            - name: ACTUAL_OPENID_SERVER_HOSTNAME
              value: "https://budgetc.nphls.com"
          volumeMounts:
            - name: data
              mountPath: /data
          livenessProbe:
            exec:
              command: ["node", "src/scripts/health-check.js"]
            initialDelaySeconds: 20
            periodSeconds: 60
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              memory: 256Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: actual-budget-cherise-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: actual-budget-cherise
  namespace: actual-budget
spec:
  type: NodePort
  selector:
    app: actual-budget-cherise
  ports:
    - port: 5007
      targetPort: 5007
      nodePort: 30507
