services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    ports:
      - '3001:3000'
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS}
    volumes:
      - ${HOMEPAGE_DIR}/config:/app/config
    restart: unless-stopped
