apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-db
  namespace: nextcloud
type: Opaque
stringData:
  # From /tank/appdata/nextcloud/docker-compose.yaml
  MYSQL_ROOT_PASSWORD: "REPLACE"
  MYSQL_PASSWORD: "REPLACE"
  REDIS_PASSWORD: "REPLACE"
  COLLABORA_PASSWORD: "REPLACE"
