apiVersion: v1
kind: Secret
metadata:
  name: immich
  namespace: immich
type: Opaque
stringData:
  # Copy values from /tank/appdata/immich/.env
  DB_PASSWORD: "REPLACE"
  DB_USERNAME: "REPLACE"
  DB_DATABASE_NAME: "REPLACE"
